### PR TITLE
Update host-meta

### PR DESCRIPTION
**Pull request by CodeFoodPixels**
Fix incorrect lrdd type

### CODE REVIEW

**Review by MrPetovan — APPROVED** [review]

**Review by wakest — APPROVED** [review]
hell yeah!

**Comment by wakest** [comment]
@CodeFoodPixels @MrPetovan hey thanks! I have never merged a pull request before!

**Comment by MrPetovan** [comment]
Yes you did! https://github.com/wakest/wake.st/pull/1

**Comment by wakest** [comment]
oh your right I guess I forgot that one!

**Pull request merged**
